// generated by Fast Light User Interface Designer (fluid) version 1.0102

#ifndef UI_h
#define UI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "MyWindow.H"
extern shape_window *DrawingBox;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *asd;
extern void flload(Fl_Menu_*, void*);
extern void flsave(Fl_Menu_*, void*);
extern void flreset(Fl_Menu_*, void*);
extern void flexit(Fl_Menu_*, void*);
extern void flsaveas(Fl_Menu_*, void*);
extern void opentexturewin(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
extern void flsetvertx(Fl_Value_Input*, void*);
extern Fl_Value_Input *flvertx;
extern void flsetverty(Fl_Value_Input*, void*);
extern Fl_Value_Input *flverty;
extern void flsetvertz(Fl_Value_Input*, void*);
extern Fl_Value_Input *flvertz;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *flvertsize;
#include <FL/Fl_Choice.H>
extern void flsetverttype(Fl_Choice*, void*);
extern Fl_Choice *flverttype;
extern void flsetlinetex(Fl_Choice*, void*);
extern Fl_Choice *fllinetex;
extern void flsetroofheight(Fl_Value_Input*, void*);
extern Fl_Value_Input *flpolyroof;
extern void flsetfloorheight(Fl_Value_Input*, void*);
extern Fl_Value_Input *flpolyfloor;
extern void flsetrooftex(Fl_Choice*, void*);
extern Fl_Choice *flrooftex;
extern void flsetfloortex(Fl_Choice*, void*);
extern Fl_Choice *flfloortex;
#include <FL/Fl_Button.H>
extern void flsetpolymode(Fl_Button*, void*);
extern Fl_Button *flpolymode;
extern void flsetobjmode(Fl_Button*, void*);
extern Fl_Button *flobjmode;
#include <FL/Fl_Dial.H>
extern void flSetVertDir(Fl_Dial*, void*);
extern Fl_Dial *VertDir;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_asd[];
extern Fl_Menu_Item menu_fllinetex[];
extern Fl_Menu_Item menu_flrooftex[];
extern Fl_Menu_Item menu_flfloortex[];
#include <FL/Fl_Browser.H>
extern Fl_Browser *fltexlist;
extern void flnewtex(Fl_Button*, void*);
extern Fl_Button *flnewtexbutton;
extern void fldeltex(Fl_Button*, void*);
extern Fl_Button *fldeltexbutton;
Fl_Double_Window* make_texture_window();
#endif
